# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class QueryGroupEntity(Model):
    """QueryGroupEntity.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param description:
    :type description: str
    :param parent_id:
    :type parent_id: str
    :param order:
    :type order: int
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'parent_id': {'key': 'parentId', 'type': 'str'},
        'order': {'key': 'order', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(QueryGroupEntity, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.description = kwargs.get('description', None)
        self.parent_id = kwargs.get('parent_id', None)
        self.order = kwargs.get('order', None)
