/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The information for CDS Organization in BAP
 *
 */
class CdsOrgInfo {
  /**
   * Create a CdsOrgInfo.
   * @property {string} [friendlyName] Gets the Cds Organization Friendly Name
   * @property {string} [url] Gets the Cds Organization Url
   * @property {string} [state] Gets the Cds Organization State
   * @property {string} [location] Gets region location of Cds Organization
   * @property {string} [environmentSku] Gets SKU of Cds Organization
   * @property {date} [expirationTime] Gets the expiration time of CDS
   * Organization if the SKU is Trial
   * @property {date} [maxAllowedExpirationTime] Gets the max allowed
   * expiration time of CDS Organization if the SKU is Trial
   */
  constructor() {
  }

  /**
   * Defines the metadata of CdsOrgInfo
   *
   * @returns {object} metadata of CdsOrgInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CdsOrgInfo',
      type: {
        name: 'Composite',
        className: 'CdsOrgInfo',
        modelProperties: {
          friendlyName: {
            required: false,
            serializedName: 'friendlyName',
            type: {
              name: 'String'
            }
          },
          url: {
            required: false,
            serializedName: 'url',
            type: {
              name: 'String'
            }
          },
          state: {
            required: false,
            serializedName: 'state',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          environmentSku: {
            required: false,
            serializedName: 'environmentSku',
            type: {
              name: 'String'
            }
          },
          expirationTime: {
            required: false,
            serializedName: 'expirationTime',
            type: {
              name: 'DateTime'
            }
          },
          maxAllowedExpirationTime: {
            required: false,
            serializedName: 'maxAllowedExpirationTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = CdsOrgInfo;
