/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Represents a Incremental Refresh Property.
 *
 */
class IncrementalRefreshProperties {
  /**
   * Create a IncrementalRefreshProperties.
   * @property {string} [entityName] Name of the entity.
   * @property {string} [detectChangesAttributeName] Column to detect changes.
   * @property {string} [filterByAttributeName] Column to get incremental data.
   * @property {string} [incrementalGranularity] Granularity of the incremental
   * refresh.
   * @property {number} [incrementalPeriods] Incremental period.
   * @property {boolean} [refreshCompletePeriods] Indicating whether to refresh
   * completed periods or not.
   * @property {number} [incrementalPeriodsOffset] Off set period.
   * @property {string} [primaryKeyAttributeName] Primary key of the entity.
   * @property {string} [rollingWindowGranularity] Rolling window granularity.
   * @property {number} [rollingWindowPeriods] Rolling window period.
   */
  constructor() {
  }

  /**
   * Defines the metadata of IncrementalRefreshProperties
   *
   * @returns {object} metadata of IncrementalRefreshProperties
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'IncrementalRefreshProperties',
      type: {
        name: 'Composite',
        className: 'IncrementalRefreshProperties',
        modelProperties: {
          entityName: {
            required: false,
            serializedName: 'entityName',
            type: {
              name: 'String'
            }
          },
          detectChangesAttributeName: {
            required: false,
            serializedName: 'detectChangesAttributeName',
            type: {
              name: 'String'
            }
          },
          filterByAttributeName: {
            required: false,
            serializedName: 'filterByAttributeName',
            type: {
              name: 'String'
            }
          },
          incrementalGranularity: {
            required: false,
            serializedName: 'incrementalGranularity',
            type: {
              name: 'String'
            }
          },
          incrementalPeriods: {
            required: false,
            serializedName: 'incrementalPeriods',
            type: {
              name: 'Number'
            }
          },
          refreshCompletePeriods: {
            required: false,
            serializedName: 'refreshCompletePeriods',
            type: {
              name: 'Boolean'
            }
          },
          incrementalPeriodsOffset: {
            required: false,
            serializedName: 'incrementalPeriodsOffset',
            type: {
              name: 'Number'
            }
          },
          primaryKeyAttributeName: {
            required: false,
            serializedName: 'primaryKeyAttributeName',
            type: {
              name: 'String'
            }
          },
          rollingWindowGranularity: {
            required: false,
            serializedName: 'rollingWindowGranularity',
            type: {
              name: 'String'
            }
          },
          rollingWindowPeriods: {
            required: false,
            serializedName: 'rollingWindowPeriods',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = IncrementalRefreshProperties;
