/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Represents a role assignment Metadata.
 *
 * @extends models['RoleAssignment']
 */
class InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1 extends models['RoleAssignment'] {
  /**
   * Create a InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1
   *
   * @returns {object} metadata of InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Instances-instanceId-RbacPrincipals-principalId-AssignmentPutRequest-1',
      type: {
        name: 'Composite',
        className: 'InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1',
        modelProperties: {
          principalId: {
            required: false,
            serializedName: 'principalId',
            type: {
              name: 'String'
            }
          },
          principalType: {
            required: false,
            serializedName: 'principalType',
            type: {
              name: 'String'
            }
          },
          roles: {
            required: false,
            serializedName: 'roles',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          instanceId: {
            required: false,
            serializedName: 'instanceId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = InstancesInstanceIdRbacPrincipalsPrincipalIdAssignmentPutRequest1;
