/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a InstancesInstanceIdV2PatchRequest1.
 * @extends models['InstanceCreationRequest']
 */
class InstancesInstanceIdV2PatchRequest1 extends models['InstanceCreationRequest'] {
  /**
   * Create a InstancesInstanceIdV2PatchRequest1.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of InstancesInstanceIdV2PatchRequest1
   *
   * @returns {object} metadata of InstancesInstanceIdV2PatchRequest1
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Instances-instanceId-V2PatchRequest-1',
      type: {
        name: 'Composite',
        className: 'InstancesInstanceIdV2PatchRequest1',
        modelProperties: {
          instanceMetadata: {
            required: false,
            serializedName: 'instanceMetadata',
            type: {
              name: 'Composite',
              className: 'InstanceMetadata'
            }
          },
          byosaResourceMetadata: {
            required: false,
            serializedName: 'byosaResourceMetadata',
            type: {
              name: 'Composite',
              className: 'ResourceMetadata'
            }
          },
          cdsResourceMetadata: {
            required: false,
            serializedName: 'cdsResourceMetadata',
            type: {
              name: 'Composite',
              className: 'ResourceMetadata'
            }
          },
          bapProvisioningType: {
            required: false,
            serializedName: 'bapProvisioningType',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = InstancesInstanceIdV2PatchRequest1;
