/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ODataErrorDetail.
 */
class ODataErrorDetail {
  /**
   * Create a ODataErrorDetail.
   * @property {string} [errorCode]
   * @property {string} [message]
   * @property {string} [target]
   */
  constructor() {
  }

  /**
   * Defines the metadata of ODataErrorDetail
   *
   * @returns {object} metadata of ODataErrorDetail
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ODataErrorDetail',
      type: {
        name: 'Composite',
        className: 'ODataErrorDetail',
        modelProperties: {
          errorCode: {
            required: false,
            serializedName: 'errorCode',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          target: {
            required: false,
            serializedName: 'target',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ODataErrorDetail;
