/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ParsingError.
 */
class ParsingError {
  /**
   * Create a ParsingError.
   * @property {array} [messages]
   * @property {string} [code] Possible values include: 'unknown',
   * 'parsingFailed', 'entityNotFound', 'attributeNotFound',
   * 'unsupportedSyntax', 'invalidOperation'
   */
  constructor() {
  }

  /**
   * Defines the metadata of ParsingError
   *
   * @returns {object} metadata of ParsingError
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ParsingError',
      type: {
        name: 'Composite',
        className: 'ParsingError',
        modelProperties: {
          messages: {
            required: false,
            serializedName: 'messages',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'LogMessageElementType',
                  type: {
                    name: 'Composite',
                    className: 'LogMessage'
                  }
              }
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ParsingError;
