/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Represents a Terms of Use for user
 *
 */
class TermsOfUse {
  /**
   * Create a TermsOfUse.
   * @property {string} [state] Possible values include: 'none', 'accepted',
   * 'declined'
   * @property {string} [version] Gets the current version of this document.
   * @property {date} [createdUtc] Gets the created time of terms acceptance.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TermsOfUse
   *
   * @returns {object} metadata of TermsOfUse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TermsOfUse',
      type: {
        name: 'Composite',
        className: 'TermsOfUse',
        modelProperties: {
          state: {
            required: false,
            serializedName: 'state',
            type: {
              name: 'String'
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'String'
            }
          },
          createdUtc: {
            required: false,
            serializedName: 'createdUtc',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = TermsOfUse;
