/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The information for workspace in CDS
 *
 */
class WorkSpaceDetail {
  /**
   * Create a WorkSpaceDetail.
   * @property {string} [name] Gets the Workspace Friendly Name
   * @property {string} [uniqueName] Gets the Cds workspace unique Name
   */
  constructor() {
  }

  /**
   * Defines the metadata of WorkSpaceDetail
   *
   * @returns {object} metadata of WorkSpaceDetail
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'WorkSpaceDetail',
      type: {
        name: 'Composite',
        className: 'WorkSpaceDetail',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          uniqueName: {
            required: false,
            serializedName: 'uniqueName',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = WorkSpaceDetail;
