/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The StringLengthCount model.
 */
public class StringLengthCount {
    /**
     * Gets or sets the string length.
     */
    @JsonProperty(value = "length")
    private Long length;

    /**
     * Gets or sets the count of string values with the Length.
     */
    @JsonProperty(value = "count")
    private Long count;

    /**
     * Get gets or sets the string length.
     *
     * @return the length value
     */
    public Long length() {
        return this.length;
    }

    /**
     * Set gets or sets the string length.
     *
     * @param length the length value to set
     * @return the StringLengthCount object itself.
     */
    public StringLengthCount withLength(Long length) {
        this.length = length;
        return this;
    }

    /**
     * Get gets or sets the count of string values with the Length.
     *
     * @return the count value
     */
    public Long count() {
        return this.count;
    }

    /**
     * Set gets or sets the count of string values with the Length.
     *
     * @param count the count value to set
     * @return the StringLengthCount object itself.
     */
    public StringLengthCount withCount(Long count) {
        this.count = count;
        return this;
    }

}
