/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AttributeSearchConfiguration model.
 */
public class AttributeSearchConfiguration {
    /**
     * Gets the attribute name.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The properties property.
     */
    @JsonProperty(value = "properties")
    private AttributeSearchProperties properties;

    /**
     * Get gets the attribute name.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set gets the attribute name.
     *
     * @param name the name value to set
     * @return the AttributeSearchConfiguration object itself.
     */
    public AttributeSearchConfiguration withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public AttributeSearchProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the AttributeSearchConfiguration object itself.
     */
    public AttributeSearchConfiguration withProperties(AttributeSearchProperties properties) {
        this.properties = properties;
        return this;
    }

}
