/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import java.util.Map;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CIResult model.
 */
public class CIResult {
    /**
     * Possible values include: 'system', 'user', 'external'.
     */
    @JsonProperty(value = "exceptionCulprit")
    private String exceptionCulprit;

    /**
     * The errorCode property.
     */
    @JsonProperty(value = "errorCode")
    private String errorCode;

    /**
     * Possible values include: 'error', 'warning'.
     */
    @JsonProperty(value = "resultSeverity")
    private String resultSeverity;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The params property.
     */
    @JsonProperty(value = "params")
    private Map<String, Object> params;

    /**
     * The ciResults property.
     */
    @JsonProperty(value = "ciResults")
    private List<CIResult> ciResults;

    /**
     * Get possible values include: 'system', 'user', 'external'.
     *
     * @return the exceptionCulprit value
     */
    public String exceptionCulprit() {
        return this.exceptionCulprit;
    }

    /**
     * Set possible values include: 'system', 'user', 'external'.
     *
     * @param exceptionCulprit the exceptionCulprit value to set
     * @return the CIResult object itself.
     */
    public CIResult withExceptionCulprit(String exceptionCulprit) {
        this.exceptionCulprit = exceptionCulprit;
        return this;
    }

    /**
     * Get the errorCode value.
     *
     * @return the errorCode value
     */
    public String errorCode() {
        return this.errorCode;
    }

    /**
     * Set the errorCode value.
     *
     * @param errorCode the errorCode value to set
     * @return the CIResult object itself.
     */
    public CIResult withErrorCode(String errorCode) {
        this.errorCode = errorCode;
        return this;
    }

    /**
     * Get possible values include: 'error', 'warning'.
     *
     * @return the resultSeverity value
     */
    public String resultSeverity() {
        return this.resultSeverity;
    }

    /**
     * Set possible values include: 'error', 'warning'.
     *
     * @param resultSeverity the resultSeverity value to set
     * @return the CIResult object itself.
     */
    public CIResult withResultSeverity(String resultSeverity) {
        this.resultSeverity = resultSeverity;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the CIResult object itself.
     */
    public CIResult withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the params value.
     *
     * @return the params value
     */
    public Map<String, Object> params() {
        return this.params;
    }

    /**
     * Set the params value.
     *
     * @param params the params value to set
     * @return the CIResult object itself.
     */
    public CIResult withParams(Map<String, Object> params) {
        this.params = params;
        return this;
    }

    /**
     * Get the ciResults value.
     *
     * @return the ciResults value
     */
    public List<CIResult> ciResults() {
        return this.ciResults;
    }

    /**
     * Set the ciResults value.
     *
     * @param ciResults the ciResults value to set
     * @return the CIResult object itself.
     */
    public CIResult withCiResults(List<CIResult> ciResults) {
        this.ciResults = ciResults;
        return this;
    }

}
