/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DeletionResponse model.
 */
public class DeletionResponse {
    /**
     * The isDeleted property.
     */
    @JsonProperty(value = "isDeleted")
    private Boolean isDeleted;

    /**
     * The issues property.
     */
    @JsonProperty(value = "issues")
    private List<DependencyValidationIssue> issues;

    /**
     * Get the isDeleted value.
     *
     * @return the isDeleted value
     */
    public Boolean isDeleted() {
        return this.isDeleted;
    }

    /**
     * Set the isDeleted value.
     *
     * @param isDeleted the isDeleted value to set
     * @return the DeletionResponse object itself.
     */
    public DeletionResponse withIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    /**
     * Get the issues value.
     *
     * @return the issues value
     */
    public List<DependencyValidationIssue> issues() {
        return this.issues;
    }

    /**
     * Set the issues value.
     *
     * @param issues the issues value to set
     * @return the DeletionResponse object itself.
     */
    public DeletionResponse withIssues(List<DependencyValidationIssue> issues) {
        this.issues = issues;
        return this;
    }

}
