/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import java.util.UUID;
import java.util.List;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The GraphTaskInfo model.
 */
public class GraphTaskInfo {
    /**
     * The taskId property.
     */
    @JsonProperty(value = "taskId")
    private UUID taskId;

    /**
     * Possible values include: 'queued', 'needsUpdate', 'running', 'failed',
     * 'timedOut', 'aborted', 'deleted', 'successful', 'skipped'.
     */
    @JsonProperty(value = "taskStatus")
    private String taskStatus;

    /**
     * Possible values include: 'none', 'ingestion', 'derivedEntity',
     * 'hierarchy', 'dataPreparation', 'map', 'realtimeM3Search', 'match',
     * 'merge', 'profileStore', 'search', 'activity', 'contact',
     * 'attributeMeasures', 'entityMeasures', 'measures', 'segmentation',
     * 'segmentMembership', 'enrichment', 'preEnrichment', 'transform',
     * 'intelligence', 'aiBuilder', 'insights', 'export', 'modelManagement',
     * 'relationship', 'roleAssignment', 'analysis', 'semanticEntity', 'all'.
     */
    @JsonProperty(value = "operationType")
    private String operationType;

    /**
     * Possible values include: 'noSubType', 'templatedMeasures',
     * 'createAnalysisModel', 'linkAnalysisModel', 'singleActivityMapping',
     * 'powerPlatform'.
     */
    @JsonProperty(value = "subType")
    private String subType;

    /**
     * The jobIds property.
     */
    @JsonProperty(value = "jobIds")
    private List<UUID> jobIds;

    /**
     * The friendlyName property.
     */
    @JsonProperty(value = "friendlyName")
    private String friendlyName;

    /**
     * The endTimestamp property.
     */
    @JsonProperty(value = "endTimestamp")
    private DateTime endTimestamp;

    /**
     * The ciError property.
     */
    @JsonProperty(value = "ciError")
    private CIResult ciError;

    /**
     * The ciErrors property.
     */
    @JsonProperty(value = "ciErrors")
    private List<CIResult> ciErrors;

    /**
     * The waitingTaskIds property.
     */
    @JsonProperty(value = "waitingTaskIds")
    private List<UUID> waitingTaskIds;

    /**
     * The additionalInfo property.
     */
    @JsonProperty(value = "additionalInfo")
    private CustomTaskInformation additionalInfo;

    /**
     * The submittedTimestamp property.
     */
    @JsonProperty(value = "submittedTimestamp")
    private DateTime submittedTimestamp;

    /**
     * Get the taskId value.
     *
     * @return the taskId value
     */
    public UUID taskId() {
        return this.taskId;
    }

    /**
     * Set the taskId value.
     *
     * @param taskId the taskId value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withTaskId(UUID taskId) {
        this.taskId = taskId;
        return this;
    }

    /**
     * Get possible values include: 'queued', 'needsUpdate', 'running', 'failed', 'timedOut', 'aborted', 'deleted', 'successful', 'skipped'.
     *
     * @return the taskStatus value
     */
    public String taskStatus() {
        return this.taskStatus;
    }

    /**
     * Set possible values include: 'queued', 'needsUpdate', 'running', 'failed', 'timedOut', 'aborted', 'deleted', 'successful', 'skipped'.
     *
     * @param taskStatus the taskStatus value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
        return this;
    }

    /**
     * Get possible values include: 'none', 'ingestion', 'derivedEntity', 'hierarchy', 'dataPreparation', 'map', 'realtimeM3Search', 'match', 'merge', 'profileStore', 'search', 'activity', 'contact', 'attributeMeasures', 'entityMeasures', 'measures', 'segmentation', 'segmentMembership', 'enrichment', 'preEnrichment', 'transform', 'intelligence', 'aiBuilder', 'insights', 'export', 'modelManagement', 'relationship', 'roleAssignment', 'analysis', 'semanticEntity', 'all'.
     *
     * @return the operationType value
     */
    public String operationType() {
        return this.operationType;
    }

    /**
     * Set possible values include: 'none', 'ingestion', 'derivedEntity', 'hierarchy', 'dataPreparation', 'map', 'realtimeM3Search', 'match', 'merge', 'profileStore', 'search', 'activity', 'contact', 'attributeMeasures', 'entityMeasures', 'measures', 'segmentation', 'segmentMembership', 'enrichment', 'preEnrichment', 'transform', 'intelligence', 'aiBuilder', 'insights', 'export', 'modelManagement', 'relationship', 'roleAssignment', 'analysis', 'semanticEntity', 'all'.
     *
     * @param operationType the operationType value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withOperationType(String operationType) {
        this.operationType = operationType;
        return this;
    }

    /**
     * Get possible values include: 'noSubType', 'templatedMeasures', 'createAnalysisModel', 'linkAnalysisModel', 'singleActivityMapping', 'powerPlatform'.
     *
     * @return the subType value
     */
    public String subType() {
        return this.subType;
    }

    /**
     * Set possible values include: 'noSubType', 'templatedMeasures', 'createAnalysisModel', 'linkAnalysisModel', 'singleActivityMapping', 'powerPlatform'.
     *
     * @param subType the subType value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withSubType(String subType) {
        this.subType = subType;
        return this;
    }

    /**
     * Get the jobIds value.
     *
     * @return the jobIds value
     */
    public List<UUID> jobIds() {
        return this.jobIds;
    }

    /**
     * Set the jobIds value.
     *
     * @param jobIds the jobIds value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withJobIds(List<UUID> jobIds) {
        this.jobIds = jobIds;
        return this;
    }

    /**
     * Get the friendlyName value.
     *
     * @return the friendlyName value
     */
    public String friendlyName() {
        return this.friendlyName;
    }

    /**
     * Set the friendlyName value.
     *
     * @param friendlyName the friendlyName value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * Get the endTimestamp value.
     *
     * @return the endTimestamp value
     */
    public DateTime endTimestamp() {
        return this.endTimestamp;
    }

    /**
     * Set the endTimestamp value.
     *
     * @param endTimestamp the endTimestamp value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withEndTimestamp(DateTime endTimestamp) {
        this.endTimestamp = endTimestamp;
        return this;
    }

    /**
     * Get the ciError value.
     *
     * @return the ciError value
     */
    public CIResult ciError() {
        return this.ciError;
    }

    /**
     * Set the ciError value.
     *
     * @param ciError the ciError value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withCiError(CIResult ciError) {
        this.ciError = ciError;
        return this;
    }

    /**
     * Get the ciErrors value.
     *
     * @return the ciErrors value
     */
    public List<CIResult> ciErrors() {
        return this.ciErrors;
    }

    /**
     * Set the ciErrors value.
     *
     * @param ciErrors the ciErrors value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withCiErrors(List<CIResult> ciErrors) {
        this.ciErrors = ciErrors;
        return this;
    }

    /**
     * Get the waitingTaskIds value.
     *
     * @return the waitingTaskIds value
     */
    public List<UUID> waitingTaskIds() {
        return this.waitingTaskIds;
    }

    /**
     * Set the waitingTaskIds value.
     *
     * @param waitingTaskIds the waitingTaskIds value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withWaitingTaskIds(List<UUID> waitingTaskIds) {
        this.waitingTaskIds = waitingTaskIds;
        return this;
    }

    /**
     * Get the additionalInfo value.
     *
     * @return the additionalInfo value
     */
    public CustomTaskInformation additionalInfo() {
        return this.additionalInfo;
    }

    /**
     * Set the additionalInfo value.
     *
     * @param additionalInfo the additionalInfo value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withAdditionalInfo(CustomTaskInformation additionalInfo) {
        this.additionalInfo = additionalInfo;
        return this;
    }

    /**
     * Get the submittedTimestamp value.
     *
     * @return the submittedTimestamp value
     */
    public DateTime submittedTimestamp() {
        return this.submittedTimestamp;
    }

    /**
     * Set the submittedTimestamp value.
     *
     * @param submittedTimestamp the submittedTimestamp value to set
     * @return the GraphTaskInfo object itself.
     */
    public GraphTaskInfo withSubmittedTimestamp(DateTime submittedTimestamp) {
        this.submittedTimestamp = submittedTimestamp;
        return this;
    }

}
