/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a Hierarchy entity used to define a B2B segment/measure.
 */
public class HierarchyDefinition {
    /**
     * Gets the Hierarchy entity fully qualified name.
     */
    @JsonProperty(value = "hierarchyEntityName")
    private String hierarchyEntityName;

    /**
     * Gets the Hierarchy entity Source attribute name.
     */
    @JsonProperty(value = "sourceAttributeName")
    private String sourceAttributeName;

    /**
     * Gets the Hierarchy entity Destination attribute name.
     */
    @JsonProperty(value = "destinationAttributeName")
    private String destinationAttributeName;

    /**
     * Get gets the Hierarchy entity fully qualified name.
     *
     * @return the hierarchyEntityName value
     */
    public String hierarchyEntityName() {
        return this.hierarchyEntityName;
    }

    /**
     * Set gets the Hierarchy entity fully qualified name.
     *
     * @param hierarchyEntityName the hierarchyEntityName value to set
     * @return the HierarchyDefinition object itself.
     */
    public HierarchyDefinition withHierarchyEntityName(String hierarchyEntityName) {
        this.hierarchyEntityName = hierarchyEntityName;
        return this;
    }

    /**
     * Get gets the Hierarchy entity Source attribute name.
     *
     * @return the sourceAttributeName value
     */
    public String sourceAttributeName() {
        return this.sourceAttributeName;
    }

    /**
     * Set gets the Hierarchy entity Source attribute name.
     *
     * @param sourceAttributeName the sourceAttributeName value to set
     * @return the HierarchyDefinition object itself.
     */
    public HierarchyDefinition withSourceAttributeName(String sourceAttributeName) {
        this.sourceAttributeName = sourceAttributeName;
        return this;
    }

    /**
     * Get gets the Hierarchy entity Destination attribute name.
     *
     * @return the destinationAttributeName value
     */
    public String destinationAttributeName() {
        return this.destinationAttributeName;
    }

    /**
     * Set gets the Hierarchy entity Destination attribute name.
     *
     * @param destinationAttributeName the destinationAttributeName value to set
     * @return the HierarchyDefinition object itself.
     */
    public HierarchyDefinition withDestinationAttributeName(String destinationAttributeName) {
        this.destinationAttributeName = destinationAttributeName;
        return this;
    }

}
