/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defaults or user selected values to store across sessions.
 */
public class History {
    /**
     * Gets history id.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Checks for already visited.
     */
    @JsonProperty(value = "viewed")
    private Boolean viewed;

    /**
     * Get gets history id.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set gets history id.
     *
     * @param id the id value to set
     * @return the History object itself.
     */
    public History withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get checks for already visited.
     *
     * @return the viewed value
     */
    public Boolean viewed() {
        return this.viewed;
    }

    /**
     * Set checks for already visited.
     *
     * @param viewed the viewed value to set
     * @return the History object itself.
     */
    public History withViewed(Boolean viewed) {
        this.viewed = viewed;
        return this;
    }

}
