/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Histogram bin.
 */
public class HistogramBin {
    /**
     * Gets or sets the lower bound.
     */
    @JsonProperty(value = "lowerBound")
    private Double lowerBound;

    /**
     * Gets or sets the upper bound.
     */
    @JsonProperty(value = "upperBound")
    private Double upperBound;

    /**
     * Gets or sets the count.
     */
    @JsonProperty(value = "count")
    private Double count;

    /**
     * Get gets or sets the lower bound.
     *
     * @return the lowerBound value
     */
    public Double lowerBound() {
        return this.lowerBound;
    }

    /**
     * Set gets or sets the lower bound.
     *
     * @param lowerBound the lowerBound value to set
     * @return the HistogramBin object itself.
     */
    public HistogramBin withLowerBound(Double lowerBound) {
        this.lowerBound = lowerBound;
        return this;
    }

    /**
     * Get gets or sets the upper bound.
     *
     * @return the upperBound value
     */
    public Double upperBound() {
        return this.upperBound;
    }

    /**
     * Set gets or sets the upper bound.
     *
     * @param upperBound the upperBound value to set
     * @return the HistogramBin object itself.
     */
    public HistogramBin withUpperBound(Double upperBound) {
        this.upperBound = upperBound;
        return this;
    }

    /**
     * Get gets or sets the count.
     *
     * @return the count value
     */
    public Double count() {
        return this.count;
    }

    /**
     * Set gets or sets the count.
     *
     * @param count the count value to set
     * @return the HistogramBin object itself.
     */
    public HistogramBin withCount(Double count) {
        this.count = count;
        return this;
    }

}
