/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import java.util.UUID;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents Entity Model.
 */
public class IC360EntityModel {
    /**
     * Gets the instance ID associated with the model.
     */
    @JsonProperty(value = "instanceId")
    private UUID instanceId;

    /**
     * Gets the dataflow ID associated with the model.
     */
    @JsonProperty(value = "dataflowId")
    private UUID dataflowId;

    /**
     * Gets the datasource ID associated with the model.
     */
    @JsonProperty(value = "datasourceId")
    private UUID datasourceId;

    /**
     * Possible values include: 'dynamics365', 'salesforce',
     * 'conflationSortAndRefine', 'conflationDeduplication',
     * 'conflationMatchPairs', 'conflationResolveConflicts', 'enriched', 'kpi',
     * 'powerQuery', 'dataPreparation', 'intelligence', 'unifiedActivity',
     * 'segmentation', 'ingestion', 'attachCdm', 'genericPrediction',
     * 'attachCds', 'unknown', 'powerPlatform', 'datahub', 'insights',
     * 'derivedEntity', 'powerPlatformSource', 'powerPlatformBYDL',
     * 'powerPlatformBYDLSource', 'semanticActivity', 'segmentMembership',
     * 'cjoData', 'eiData', 'hierarchy'.
     */
    @JsonProperty(value = "dataflowType")
    private String dataflowType;

    /**
     * Gets entities in the model.
     */
    @JsonProperty(value = "entities")
    private List<IEntityMetadata> entities;

    /**
     * Get gets the instance ID associated with the model.
     *
     * @return the instanceId value
     */
    public UUID instanceId() {
        return this.instanceId;
    }

    /**
     * Set gets the instance ID associated with the model.
     *
     * @param instanceId the instanceId value to set
     * @return the IC360EntityModel object itself.
     */
    public IC360EntityModel withInstanceId(UUID instanceId) {
        this.instanceId = instanceId;
        return this;
    }

    /**
     * Get gets the dataflow ID associated with the model.
     *
     * @return the dataflowId value
     */
    public UUID dataflowId() {
        return this.dataflowId;
    }

    /**
     * Set gets the dataflow ID associated with the model.
     *
     * @param dataflowId the dataflowId value to set
     * @return the IC360EntityModel object itself.
     */
    public IC360EntityModel withDataflowId(UUID dataflowId) {
        this.dataflowId = dataflowId;
        return this;
    }

    /**
     * Get gets the datasource ID associated with the model.
     *
     * @return the datasourceId value
     */
    public UUID datasourceId() {
        return this.datasourceId;
    }

    /**
     * Set gets the datasource ID associated with the model.
     *
     * @param datasourceId the datasourceId value to set
     * @return the IC360EntityModel object itself.
     */
    public IC360EntityModel withDatasourceId(UUID datasourceId) {
        this.datasourceId = datasourceId;
        return this;
    }

    /**
     * Get possible values include: 'dynamics365', 'salesforce', 'conflationSortAndRefine', 'conflationDeduplication', 'conflationMatchPairs', 'conflationResolveConflicts', 'enriched', 'kpi', 'powerQuery', 'dataPreparation', 'intelligence', 'unifiedActivity', 'segmentation', 'ingestion', 'attachCdm', 'genericPrediction', 'attachCds', 'unknown', 'powerPlatform', 'datahub', 'insights', 'derivedEntity', 'powerPlatformSource', 'powerPlatformBYDL', 'powerPlatformBYDLSource', 'semanticActivity', 'segmentMembership', 'cjoData', 'eiData', 'hierarchy'.
     *
     * @return the dataflowType value
     */
    public String dataflowType() {
        return this.dataflowType;
    }

    /**
     * Set possible values include: 'dynamics365', 'salesforce', 'conflationSortAndRefine', 'conflationDeduplication', 'conflationMatchPairs', 'conflationResolveConflicts', 'enriched', 'kpi', 'powerQuery', 'dataPreparation', 'intelligence', 'unifiedActivity', 'segmentation', 'ingestion', 'attachCdm', 'genericPrediction', 'attachCds', 'unknown', 'powerPlatform', 'datahub', 'insights', 'derivedEntity', 'powerPlatformSource', 'powerPlatformBYDL', 'powerPlatformBYDLSource', 'semanticActivity', 'segmentMembership', 'cjoData', 'eiData', 'hierarchy'.
     *
     * @param dataflowType the dataflowType value to set
     * @return the IC360EntityModel object itself.
     */
    public IC360EntityModel withDataflowType(String dataflowType) {
        this.dataflowType = dataflowType;
        return this;
    }

    /**
     * Get gets entities in the model.
     *
     * @return the entities value
     */
    public List<IEntityMetadata> entities() {
        return this.entities;
    }

    /**
     * Set gets entities in the model.
     *
     * @param entities the entities value to set
     * @return the IC360EntityModel object itself.
     */
    public IC360EntityModel withEntities(List<IEntityMetadata> entities) {
        this.entities = entities;
        return this;
    }

}
