/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;


/**
 * Represents metadata for a measure (or KPI).
 */
public class InstancesInstanceIdManageMeasuresMeasureNamePutRequest extends MeasureMetadata {
}
