/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Base class to represent a measure expression.
 */
public class MeasureExpression {
    /**
     * Possible values include: 'constant', 'property', 'memberAccess',
     * 'functionCall', 'and', 'or', 'equals', 'notEquals', 'greaterThan',
     * 'greaterThanOrEqualTo', 'lessThan', 'lessThanOrEqualTo', 'contains',
     * 'startsWith', 'endsWith', 'isNull', 'isNotNull', 'negate', 'add',
     * 'subtract', 'multiply', 'divide', 'modulo', 'exponent', 'today', 'now'.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * Get possible values include: 'constant', 'property', 'memberAccess', 'functionCall', 'and', 'or', 'equals', 'notEquals', 'greaterThan', 'greaterThanOrEqualTo', 'lessThan', 'lessThanOrEqualTo', 'contains', 'startsWith', 'endsWith', 'isNull', 'isNotNull', 'negate', 'add', 'subtract', 'multiply', 'divide', 'modulo', 'exponent', 'today', 'now'.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set possible values include: 'constant', 'property', 'memberAccess', 'functionCall', 'and', 'or', 'equals', 'notEquals', 'greaterThan', 'greaterThanOrEqualTo', 'lessThan', 'lessThanOrEqualTo', 'contains', 'startsWith', 'endsWith', 'isNull', 'isNotNull', 'negate', 'add', 'subtract', 'multiply', 'divide', 'modulo', 'exponent', 'today', 'now'.
     *
     * @param kind the kind value to set
     * @return the MeasureExpression object itself.
     */
    public MeasureExpression withKind(String kind) {
        this.kind = kind;
        return this;
    }

}
