/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a mapping  that can store all user ids associated with the email.
 */
public class PortalSettings {
    /**
     * Gets a value indicating whether the user has seen the all apps (welcome)
     * page.
     */
    @JsonProperty(value = "isExistingUser")
    private Boolean isExistingUser;

    /**
     * Gets a value indicating whether the user has seen the all apps (welcome)
     * page.
     */
    @JsonProperty(value = "showDefaultHomePage")
    private Boolean showDefaultHomePage;

    /**
     * Gets a value indicating whether the user has seen the all apps (welcome)
     * page.
     */
    @JsonProperty(value = "proTagger")
    private Boolean proTagger;

    /**
     * Get gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @return the isExistingUser value
     */
    public Boolean isExistingUser() {
        return this.isExistingUser;
    }

    /**
     * Set gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @param isExistingUser the isExistingUser value to set
     * @return the PortalSettings object itself.
     */
    public PortalSettings withIsExistingUser(Boolean isExistingUser) {
        this.isExistingUser = isExistingUser;
        return this;
    }

    /**
     * Get gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @return the showDefaultHomePage value
     */
    public Boolean showDefaultHomePage() {
        return this.showDefaultHomePage;
    }

    /**
     * Set gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @param showDefaultHomePage the showDefaultHomePage value to set
     * @return the PortalSettings object itself.
     */
    public PortalSettings withShowDefaultHomePage(Boolean showDefaultHomePage) {
        this.showDefaultHomePage = showDefaultHomePage;
        return this;
    }

    /**
     * Get gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @return the proTagger value
     */
    public Boolean proTagger() {
        return this.proTagger;
    }

    /**
     * Set gets a value indicating whether the user has seen the all apps (welcome) page.
     *
     * @param proTagger the proTagger value to set
     * @return the PortalSettings object itself.
     */
    public PortalSettings withProTagger(Boolean proTagger) {
        this.proTagger = proTagger;
        return this;
    }

}
