/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ProfileStoreModuleRunInfo model.
 */
public class ProfileStoreModuleRunInfo {
    /**
     * LastSuccessfulRunId Info for every fullyQualifiedEntity.
     */
    @JsonProperty(value = "runInfo")
    private Map<String, String> runInfo;

    /**
     * Get lastSuccessfulRunId Info for every fullyQualifiedEntity.
     *
     * @return the runInfo value
     */
    public Map<String, String> runInfo() {
        return this.runInfo;
    }

    /**
     * Set lastSuccessfulRunId Info for every fullyQualifiedEntity.
     *
     * @param runInfo the runInfo value to set
     * @return the ProfileStoreModuleRunInfo object itself.
     */
    public ProfileStoreModuleRunInfo withRunInfo(Map<String, String> runInfo) {
        this.runInfo = runInfo;
        return this;
    }

}
