/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.dynamics.customerinsights.apiclient.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a Terms of Use for user.
 */
public class TermsOfUse {
    /**
     * Possible values include: 'none', 'accepted', 'declined'.
     */
    @JsonProperty(value = "state")
    private String state;

    /**
     * Gets the current version of this document.
     */
    @JsonProperty(value = "version")
    private String version;

    /**
     * Gets the created time of terms acceptance.
     */
    @JsonProperty(value = "createdUtc")
    private DateTime createdUtc;

    /**
     * Get possible values include: 'none', 'accepted', 'declined'.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set possible values include: 'none', 'accepted', 'declined'.
     *
     * @param state the state value to set
     * @return the TermsOfUse object itself.
     */
    public TermsOfUse withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get gets the current version of this document.
     *
     * @return the version value
     */
    public String version() {
        return this.version;
    }

    /**
     * Set gets the current version of this document.
     *
     * @param version the version value to set
     * @return the TermsOfUse object itself.
     */
    public TermsOfUse withVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * Get gets the created time of terms acceptance.
     *
     * @return the createdUtc value
     */
    public DateTime createdUtc() {
        return this.createdUtc;
    }

    /**
     * Set gets the created time of terms acceptance.
     *
     * @param createdUtc the createdUtc value to set
     * @return the TermsOfUse object itself.
     */
    public TermsOfUse withCreatedUtc(DateTime createdUtc) {
        this.createdUtc = createdUtc;
        return this;
    }

}
