// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ODataError
    {
        /// <summary>
        /// Initializes a new instance of the ODataError class.
        /// </summary>
        public ODataError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ODataError class.
        /// </summary>
        public ODataError(string errorCode = default(string), string message = default(string), string target = default(string), IList<ODataErrorDetail> details = default(IList<ODataErrorDetail>), ODataInnerError innerError = default(ODataInnerError), IList<ODataInstanceAnnotation> instanceAnnotations = default(IList<ODataInstanceAnnotation>), ODataTypeAnnotation typeAnnotation = default(ODataTypeAnnotation))
        {
            ErrorCode = errorCode;
            Message = message;
            Target = target;
            Details = details;
            InnerError = innerError;
            InstanceAnnotations = instanceAnnotations;
            TypeAnnotation = typeAnnotation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<ODataErrorDetail> Details { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerError")]
        public ODataInnerError InnerError { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instanceAnnotations")]
        public IList<ODataInstanceAnnotation> InstanceAnnotations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeAnnotation")]
        public ODataTypeAnnotation TypeAnnotation { get; set; }

    }
}
