// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SourceLocation
    {
        /// <summary>
        /// Initializes a new instance of the SourceLocation class.
        /// </summary>
        public SourceLocation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SourceLocation class.
        /// </summary>
        public SourceLocation(int? line = default(int?), int? column = default(int?))
        {
            Line = line;
            Column = column;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "line")]
        public int? Line { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "column")]
        public int? Column { get; set; }

    }
}
