// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Api Error response class (DTO)
    /// </summary>
    public partial class ApiErrorResult
    {
        /// <summary>
        /// Initializes a new instance of the ApiErrorResult class.
        /// </summary>
        public ApiErrorResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiErrorResult class.
        /// </summary>
        /// <param name="exceptionCulprit">Possible values include: 'system',
        /// 'user', 'external'</param>
        /// <param name="resultSeverity">Possible values include: 'error',
        /// 'warning'</param>
        /// <param name="message">Message providing more information about the
        /// event.</param>
        /// <param name="ciResults">List of CiResult contining CI result error
        /// code and information (if any).</param>
        public ApiErrorResult(object exception = default(object), string httpStatusCode = default(string), string exceptionCulprit = default(string), string errorCode = default(string), string resultSeverity = default(string), string message = default(string), IDictionary<string, object> paramsProperty = default(IDictionary<string, object>), IList<CIResult> ciResults = default(IList<CIResult>))
        {
            Exception = exception;
            HttpStatusCode = httpStatusCode;
            ExceptionCulprit = exceptionCulprit;
            ErrorCode = errorCode;
            ResultSeverity = resultSeverity;
            Message = message;
            ParamsProperty = paramsProperty;
            CiResults = ciResults;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exception")]
        public object Exception { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "httpStatusCode")]
        public string HttpStatusCode { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'system', 'user', 'external'
        /// </summary>
        [JsonProperty(PropertyName = "exceptionCulprit")]
        public string ExceptionCulprit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'error', 'warning'
        /// </summary>
        [JsonProperty(PropertyName = "resultSeverity")]
        public string ResultSeverity { get; set; }

        /// <summary>
        /// Gets or sets message providing more information about the event.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "params")]
        public IDictionary<string, object> ParamsProperty { get; set; }

        /// <summary>
        /// Gets or sets list of CiResult contining CI result error code and
        /// information (if any).
        /// </summary>
        [JsonProperty(PropertyName = "ciResults")]
        public IList<CIResult> CiResults { get; set; }

    }
}
