// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The information for datalake folder in CDS
    /// </summary>
    public partial class DatalakeFolderDetail
    {
        /// <summary>
        /// Initializes a new instance of the DatalakeFolderDetail class.
        /// </summary>
        public DatalakeFolderDetail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatalakeFolderDetail class.
        /// </summary>
        /// <param name="name">Gets the datalake folder Friendly Name</param>
        /// <param name="uniqueName">Gets the Cds datalake folder unique
        /// Name</param>
        public DatalakeFolderDetail(string name = default(string), string uniqueName = default(string))
        {
            Name = name;
            UniqueName = uniqueName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the datalake folder Friendly Name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets the Cds datalake folder unique Name
        /// </summary>
        [JsonProperty(PropertyName = "uniqueName")]
        public string UniqueName { get; set; }

    }
}
