// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a dismissed notification.
    /// </summary>
    public partial class DismissedNotification
    {
        /// <summary>
        /// Initializes a new instance of the DismissedNotification class.
        /// </summary>
        public DismissedNotification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DismissedNotification class.
        /// </summary>
        /// <param name="notificationId">Gets the unique id of the
        /// notification</param>
        /// <param name="notificationExpiryTimeUtc">Gets the expiration UTC
        /// date time of this notification.</param>
        public DismissedNotification(System.Guid? notificationId = default(System.Guid?), System.DateTime? notificationExpiryTimeUtc = default(System.DateTime?))
        {
            NotificationId = notificationId;
            NotificationExpiryTimeUtc = notificationExpiryTimeUtc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the unique id of the notification
        /// </summary>
        [JsonProperty(PropertyName = "notificationId")]
        public System.Guid? NotificationId { get; set; }

        /// <summary>
        /// Gets the expiration UTC date time of this notification.
        /// </summary>
        [JsonProperty(PropertyName = "notificationExpiryTimeUtc")]
        public System.DateTime? NotificationExpiryTimeUtc { get; set; }

    }
}
