// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents Entity Data Profile information.
    /// </summary>
    public partial class EntityDataProfile
    {
        /// <summary>
        /// Initializes a new instance of the EntityDataProfile class.
        /// </summary>
        public EntityDataProfile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EntityDataProfile class.
        /// </summary>
        /// <param name="qualifiedEntityName">Qualified Entity Name.</param>
        /// <param name="rowCount">Row count.</param>
        /// <param name="quarantineRowCount">Quarentine row count</param>
        /// <param name="profilingDate">Date for Profiling.</param>
        /// <param name="profiledAttributes">Profiling attributes.</param>
        /// <param name="corruptAttributes">Respresents currupt
        /// attributes.</param>
        /// <param name="attributeDataProfiles">Contains all the attributes
        /// data profiles.</param>
        public EntityDataProfile(string qualifiedEntityName = default(string), long? rowCount = default(long?), long? quarantineRowCount = default(long?), System.DateTime? profilingDate = default(System.DateTime?), string profiledAttributes = default(string), string corruptAttributes = default(string), IList<AttributeDataProfile> attributeDataProfiles = default(IList<AttributeDataProfile>))
        {
            QualifiedEntityName = qualifiedEntityName;
            RowCount = rowCount;
            QuarantineRowCount = quarantineRowCount;
            ProfilingDate = profilingDate;
            ProfiledAttributes = profiledAttributes;
            CorruptAttributes = corruptAttributes;
            AttributeDataProfiles = attributeDataProfiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets qualified Entity Name.
        /// </summary>
        [JsonProperty(PropertyName = "qualifiedEntityName")]
        public string QualifiedEntityName { get; set; }

        /// <summary>
        /// Gets or sets row count.
        /// </summary>
        [JsonProperty(PropertyName = "rowCount")]
        public long? RowCount { get; set; }

        /// <summary>
        /// Gets or sets quarentine row count
        /// </summary>
        [JsonProperty(PropertyName = "quarantineRowCount")]
        public long? QuarantineRowCount { get; set; }

        /// <summary>
        /// Gets or sets date for Profiling.
        /// </summary>
        [JsonProperty(PropertyName = "profilingDate")]
        public System.DateTime? ProfilingDate { get; set; }

        /// <summary>
        /// Gets or sets profiling attributes.
        /// </summary>
        [JsonProperty(PropertyName = "profiledAttributes")]
        public string ProfiledAttributes { get; set; }

        /// <summary>
        /// Gets or sets respresents currupt attributes.
        /// </summary>
        [JsonProperty(PropertyName = "corruptAttributes")]
        public string CorruptAttributes { get; set; }

        /// <summary>
        /// Gets or sets contains all the attributes data profiles.
        /// </summary>
        [JsonProperty(PropertyName = "attributeDataProfiles")]
        public IList<AttributeDataProfile> AttributeDataProfiles { get; set; }

    }
}
