// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a Incremental Refresh Property.
    /// </summary>
    public partial class IncrementalRefreshProperties
    {
        /// <summary>
        /// Initializes a new instance of the IncrementalRefreshProperties
        /// class.
        /// </summary>
        public IncrementalRefreshProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IncrementalRefreshProperties
        /// class.
        /// </summary>
        /// <param name="entityName">Name of the entity.</param>
        /// <param name="detectChangesAttributeName">Column to detect
        /// changes.</param>
        /// <param name="filterByAttributeName">Column to get incremental
        /// data.</param>
        /// <param name="incrementalGranularity">Granularity of the incremental
        /// refresh.</param>
        /// <param name="incrementalPeriods">Incremental period.</param>
        /// <param name="refreshCompletePeriods">Indicating whether to refresh
        /// completed periods or not.</param>
        /// <param name="incrementalPeriodsOffset">Off set period.</param>
        /// <param name="primaryKeyAttributeName">Primary key of the
        /// entity.</param>
        /// <param name="rollingWindowGranularity">Rolling window
        /// granularity.</param>
        /// <param name="rollingWindowPeriods">Rolling window period.</param>
        public IncrementalRefreshProperties(string entityName = default(string), string detectChangesAttributeName = default(string), string filterByAttributeName = default(string), string incrementalGranularity = default(string), int? incrementalPeriods = default(int?), bool? refreshCompletePeriods = default(bool?), int? incrementalPeriodsOffset = default(int?), string primaryKeyAttributeName = default(string), string rollingWindowGranularity = default(string), int? rollingWindowPeriods = default(int?))
        {
            EntityName = entityName;
            DetectChangesAttributeName = detectChangesAttributeName;
            FilterByAttributeName = filterByAttributeName;
            IncrementalGranularity = incrementalGranularity;
            IncrementalPeriods = incrementalPeriods;
            RefreshCompletePeriods = refreshCompletePeriods;
            IncrementalPeriodsOffset = incrementalPeriodsOffset;
            PrimaryKeyAttributeName = primaryKeyAttributeName;
            RollingWindowGranularity = rollingWindowGranularity;
            RollingWindowPeriods = rollingWindowPeriods;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name of the entity.
        /// </summary>
        [JsonProperty(PropertyName = "entityName")]
        public string EntityName { get; set; }

        /// <summary>
        /// Gets or sets column to detect changes.
        /// </summary>
        [JsonProperty(PropertyName = "detectChangesAttributeName")]
        public string DetectChangesAttributeName { get; set; }

        /// <summary>
        /// Gets or sets column to get incremental data.
        /// </summary>
        [JsonProperty(PropertyName = "filterByAttributeName")]
        public string FilterByAttributeName { get; set; }

        /// <summary>
        /// Gets or sets granularity of the incremental refresh.
        /// </summary>
        [JsonProperty(PropertyName = "incrementalGranularity")]
        public string IncrementalGranularity { get; set; }

        /// <summary>
        /// Gets or sets incremental period.
        /// </summary>
        [JsonProperty(PropertyName = "incrementalPeriods")]
        public int? IncrementalPeriods { get; set; }

        /// <summary>
        /// Gets or sets indicating whether to refresh completed periods or
        /// not.
        /// </summary>
        [JsonProperty(PropertyName = "refreshCompletePeriods")]
        public bool? RefreshCompletePeriods { get; set; }

        /// <summary>
        /// Gets or sets off set period.
        /// </summary>
        [JsonProperty(PropertyName = "incrementalPeriodsOffset")]
        public int? IncrementalPeriodsOffset { get; set; }

        /// <summary>
        /// Gets or sets primary key of the entity.
        /// </summary>
        [JsonProperty(PropertyName = "primaryKeyAttributeName")]
        public string PrimaryKeyAttributeName { get; set; }

        /// <summary>
        /// Gets or sets rolling window granularity.
        /// </summary>
        [JsonProperty(PropertyName = "rollingWindowGranularity")]
        public string RollingWindowGranularity { get; set; }

        /// <summary>
        /// Gets or sets rolling window period.
        /// </summary>
        [JsonProperty(PropertyName = "rollingWindowPeriods")]
        public int? RollingWindowPeriods { get; set; }

    }
}
