// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a variable condition.
    /// </summary>
    public partial class MeasureVariableCondition
    {
        /// <summary>
        /// Initializes a new instance of the MeasureVariableCondition class.
        /// </summary>
        public MeasureVariableCondition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeasureVariableCondition class.
        /// </summary>
        /// <param name="kind">Possible values include: 'replaceNulls',
        /// 'replaceTargetValues'</param>
        public MeasureVariableCondition(string kind = default(string))
        {
            Kind = kind;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'replaceNulls',
        /// 'replaceTargetValues'
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

    }
}
