// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Settings to track notifications that users have viewed and dismissed
    /// </summary>
    public partial class Notifications
    {
        /// <summary>
        /// Initializes a new instance of the Notifications class.
        /// </summary>
        public Notifications()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Notifications class.
        /// </summary>
        public Notifications(History history = default(History))
        {
            History = history;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "history")]
        public History History { get; set; }

    }
}
