// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OkObjectResult
    {
        /// <summary>
        /// Initializes a new instance of the OkObjectResult class.
        /// </summary>
        public OkObjectResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OkObjectResult class.
        /// </summary>
        public OkObjectResult(object value = default(object), IList<object> formatters = default(IList<object>), IList<string> contentTypes = default(IList<string>), string declaredType = default(string), int? statusCode = default(int?))
        {
            Value = value;
            Formatters = formatters;
            ContentTypes = contentTypes;
            DeclaredType = declaredType;
            StatusCode = statusCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public object Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formatters")]
        public IList<object> Formatters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentTypes")]
        public IList<string> ContentTypes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "declaredType")]
        public string DeclaredType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

    }
}
