// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents the status of a provisioning operation
    /// </summary>
    public partial class ProvisioningStatus
    {
        /// <summary>
        /// Initializes a new instance of the ProvisioningStatus class.
        /// </summary>
        public ProvisioningStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProvisioningStatus class.
        /// </summary>
        /// <param name="totalSteps">Gets the total number of steps in the
        /// provisioning operation.</param>
        /// <param name="currentStep">Gets the current step in the provisioning
        /// operation.</param>
        /// <param name="currentOperation">Possible values include: 'starting',
        /// 'creating', 'loadingData', 'completed'</param>
        /// <param name="createdTimeUtc">Gets the instance created
        /// time.</param>
        /// <param name="lastUpdatedTimeUtc">Gets the instance last updated
        /// time.</param>
        /// <param name="errors">Gets a list of provisioning errors.</param>
        public ProvisioningStatus(int? totalSteps = default(int?), int? currentStep = default(int?), string currentOperation = default(string), System.DateTime? createdTimeUtc = default(System.DateTime?), System.DateTime? lastUpdatedTimeUtc = default(System.DateTime?), IList<InstanceProvisioningError> errors = default(IList<InstanceProvisioningError>))
        {
            TotalSteps = totalSteps;
            CurrentStep = currentStep;
            CurrentOperation = currentOperation;
            CreatedTimeUtc = createdTimeUtc;
            LastUpdatedTimeUtc = lastUpdatedTimeUtc;
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the total number of steps in the provisioning operation.
        /// </summary>
        [JsonProperty(PropertyName = "totalSteps")]
        public int? TotalSteps { get; set; }

        /// <summary>
        /// Gets the current step in the provisioning operation.
        /// </summary>
        [JsonProperty(PropertyName = "currentStep")]
        public int? CurrentStep { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'starting', 'creating',
        /// 'loadingData', 'completed'
        /// </summary>
        [JsonProperty(PropertyName = "currentOperation")]
        public string CurrentOperation { get; set; }

        /// <summary>
        /// Gets the instance created time.
        /// </summary>
        [JsonProperty(PropertyName = "createdTimeUtc")]
        public System.DateTime? CreatedTimeUtc { get; set; }

        /// <summary>
        /// Gets the instance last updated time.
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdatedTimeUtc")]
        public System.DateTime? LastUpdatedTimeUtc { get; set; }

        /// <summary>
        /// Gets a list of provisioning errors.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<InstanceProvisioningError> Errors { get; set; }

    }
}
