// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Dynamics.CustomerInsights.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a SegmentRowset Stat.
    /// </summary>
    public partial class SegmentRowsetStat
    {
        /// <summary>
        /// Initializes a new instance of the SegmentRowsetStat class.
        /// </summary>
        public SegmentRowsetStat()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SegmentRowsetStat class.
        /// </summary>
        /// <param name="rowsetId">Gets a Rowset Id for the Rowset
        /// Stat.</param>
        /// <param name="rowsetCount">Gets a Rowset Count for the Rowset
        /// Id.</param>
        public SegmentRowsetStat(System.Guid? rowsetId = default(System.Guid?), long? rowsetCount = default(long?))
        {
            RowsetId = rowsetId;
            RowsetCount = rowsetCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets a Rowset Id for the Rowset Stat.
        /// </summary>
        [JsonProperty(PropertyName = "rowsetId")]
        public System.Guid? RowsetId { get; set; }

        /// <summary>
        /// Gets a Rowset Count for the Rowset Id.
        /// </summary>
        [JsonProperty(PropertyName = "rowsetCount")]
        public long? RowsetCount { get; set; }

    }
}
