/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Annotation.
 */
class Annotation {
  /**
   * Create a Annotation.
   * @property {string} [name]
   * @property {string} [value]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Annotation
   *
   * @returns {object} metadata of Annotation
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Annotation',
      type: {
        name: 'Composite',
        className: 'Annotation',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Annotation;
