/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Numerical quantiles.
 *
 */
class Quantiles {
  /**
   * Create a Quantiles.
   * @property {number} [p0D1] Gets or sets the 1% quantile.
   * @property {number} [p1] Gets or sets the 1% quantile.
   * @property {number} [p5] Gets or sets the 5% quantile.
   * @property {number} [p25] Gets or sets the 25% quantile.
   * @property {number} [p50] Gets or sets the 50% quantile.
   * @property {number} [p75] Gets or sets the 75% quantile.
   * @property {number} [p95] Gets or sets the 95% quantile.
   * @property {number} [p99] Gets or sets the 99% quantile.
   * @property {number} [p99D9] Gets or sets the 9% quantile.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Quantiles
   *
   * @returns {object} metadata of Quantiles
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Quantiles',
      type: {
        name: 'Composite',
        className: 'Quantiles',
        modelProperties: {
          p0D1: {
            required: false,
            serializedName: 'p0D1',
            type: {
              name: 'Number'
            }
          },
          p1: {
            required: false,
            serializedName: 'p1',
            type: {
              name: 'Number'
            }
          },
          p5: {
            required: false,
            serializedName: 'p5',
            type: {
              name: 'Number'
            }
          },
          p25: {
            required: false,
            serializedName: 'p25',
            type: {
              name: 'Number'
            }
          },
          p50: {
            required: false,
            serializedName: 'p50',
            type: {
              name: 'Number'
            }
          },
          p75: {
            required: false,
            serializedName: 'p75',
            type: {
              name: 'Number'
            }
          },
          p95: {
            required: false,
            serializedName: 'p95',
            type: {
              name: 'Number'
            }
          },
          p99: {
            required: false,
            serializedName: 'p99',
            type: {
              name: 'Number'
            }
          },
          p99D9: {
            required: false,
            serializedName: 'p99D9',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Quantiles;
