/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a QueryGroupEntity.
 */
class QueryGroupEntity {
  /**
   * Create a QueryGroupEntity.
   * @property {string} [id]
   * @property {string} [name]
   * @property {string} [description]
   * @property {string} [parentId]
   * @property {number} [order]
   */
  constructor() {
  }

  /**
   * Defines the metadata of QueryGroupEntity
   *
   * @returns {object} metadata of QueryGroupEntity
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'QueryGroupEntity',
      type: {
        name: 'Composite',
        className: 'QueryGroupEntity',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          parentId: {
            required: false,
            serializedName: 'parentId',
            type: {
              name: 'String'
            }
          },
          order: {
            required: false,
            serializedName: 'order',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = QueryGroupEntity;
