/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a SelectionReason.
 */
class SelectionReason {
  /**
   * Create a SelectionReason.
   * @property {string} [code] Possible values include: 'unknown', 'requested',
   * 'firstRun', 'unsuccessful', 'lastRunSkipped', 'alreadyRunning',
   * 'modifiedInputs', 'upstreamRerunning', 'dependantSystemNode',
   * 'dependsOnMerge'
   * @property {string} [details]
   */
  constructor() {
  }

  /**
   * Defines the metadata of SelectionReason
   *
   * @returns {object} metadata of SelectionReason
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SelectionReason',
      type: {
        name: 'Composite',
        className: 'SelectionReason',
        modelProperties: {
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          details: {
            required: false,
            serializedName: 'details',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SelectionReason;
